epochs: 400
batch_size: 128
opt: adamw
lr: 0.003
weight_decay: 0.05
lr_scheduler: cosineannealinglr
lr_min: 0.00001
lr_warmup_method: linear
lr_warmup_epochs: 32
label_smoothing: 0.1
mixup_alpha: 0.8
clip_grad_norm: 1
interpolation: bicubic
auto_augment: ta_wide
policy_magnitude: 15
model_ema: true
val_resize_size: 224
val_crop_size: 224
train_crop_size: 224
amp: true
model_ema_steps: 32
transformer_embedding_decay: 0
sync_bn: true
