epochs: 600
batch_size: 128
lr: 0.5
lr_scheduler: cosineannealinglr
lr_warmup_method: linear
lr_warmup_epochs: 5
label_smoothing: 0.1
mixup_alpha: 0.2
auto_augment: ta_wide
random_erase: 0.1
weight_decay: 0.00002
norm_weight_decay: 0.0
clip_grad_norm: 1
ra_sampler: true
cutmix_alpha: 1.0
model_ema: true
val_resize_size: 232
