batch_size: 128
lr: 0.5
lr_scheduler: cosineannealinglr
lr_warmup_epochs: 5
lr_warmup_method: linear
auto_augment: ta_wide
epochs: 600
random_erase: 0.1
label_smoothing: 0.1
mixup_alpha: 0.2
cutmix_alpha: 1.0
weight_decay: 0.00002
norm_weight_decay: 0.0
train_crop_size: 480
model_ema: true
val_crop_size: 480
val_resize_size: 480
ra_sampler: true
ra_reps: 4
