batch_size: 128
opt: adamw
lr: 0.001
lr_scheduler: cosineannealinglr
lr_warmup_epochs: 5
lr_warmup_method: linear
auto_augment: ta_wide
epochs: 600
random_erase: 0.1
label_smoothing: 0.1
mixup_alpha: 0.2
cutmix_alpha: 1.0
weight_decay: 0.05
norm_weight_decay: 0.0
train_crop_size: 176
model_ema: true
val_resize_size: 230
ra_sampler: true
ra_reps: 4
